### ISSUE TITLE
If theme defined in config.yml buttons don't work in modal editor

### ISSUE THREAD

**Issue by MattyBalaam** [nathancox/silverstripe-codeeditorfield#12]
I've had an issue which took me a while to track down, but eventually I realised that setting theme in config.yml e.g.

```
SSViewer:
  theme: 'myTheme'
```

Breaks the word-wrap and theme buttons in the modal editor. Instead, they simply close the modal.

**Comment by nathancox** [comment]
Odd...which versions of SilverStripe and CodeEditorField are you using?

**Comment by MattyBalaam** [comment]
OK, I have narrowed it down more. My theme has its own templates/forms/FormField_holder.ss, and the presence of this causes the issue. Even if the file contents are exactly the same as in the Framework/templates/forms folder.

This is with CodeEditorField 1.3, and can reproduce on every 3.x I've tried: 3.6.1, 3.5.4, and 3.3.0

**Comment by MattyBalaam** [comment]
It seems to not use a CompositeField in the broken version.

![image](https://user-images.githubusercontent.com/1246923/28407384-dfa65c1e-6d2b-11e7-8573-df744bc962ac.png)

**Comment by nathancox** [comment]
Hi, I couldn't reproduce the issues you're seeing exactly but it did turn out that the popup was using the theme's form templates, which isn't what we want.  I just did a 1.3.1 release that makes the TinyMCECodeEditor controller extend LeftAndMain which solves that issue, at least.  Give it a shot and let me know if it fixes the problems you're having.

**Comment by MattyBalaam** [comment]
Good work. It might take a while for me to test this for my case - I've left a company I was using SilverStripe at on a daily basis - but I will try and remember to look. I'm almost certain this will have solved the issue though from the sounds of it.
